parameters:
  name: ''
  queue: ''

phases:
- phase: ${{ parameters.name }}
  queue: ${{ parameters.queue }}
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.0.x
      performMultiLevelLookup: true 

  - task: DotNetCoreCLI@2
    displayName: Build2
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration Release' # Update this to match your need
