parameters:
  name: ''
  queue: ''

phases:
- phase: ${{ parameters.name }}
  queue: ${{ parameters.queue }}
  steps:
  - task: UseDotNet@21
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

