trigger:
- master

stages:
- stage: Build
  jobs:
  - job: build
    strategy:
      matrix:
        linux: { imageName: "ubuntu-18.04" }
        mac: { imageName: "macos-10.14" }
        windows: { imageName: "windows-2019" }
      maxParallel: 3
    pool:
      vmImage: $(imageName)
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true